name: Test 

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Test front
        run: npm run test:ts:front

      - name: Test back
        run: npm run test:ts:back

      - name: Build package
        run: npm run build 

      - name: Verify package 
        run: npm run verify
